services:
  web1:
    build: ./web1
    ports:
      - 3001:3000
    container_name: web1
    networks:
      - ha_net
  web2:
    build: ./web2
    ports:
      - 3002:3000
    container_name: web2
    networks:
      - ha_net
  haproxy1:
    build: ./haproxy1
    container_name: haproxy1
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - ha_net
  haproxy2:
    build: ./haproxy2
    container_name: haproxy2
    restart: unless-stopped
    ports:
      - "8082:8080"
    networks:
      - ha_net
networks:
  ha_net:
    external: true